# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 537)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_widget = QtWidgets.QTableWidget(self.centralwidget)
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(0)
        self.table_widget.setRowCount(0)
        self.horizontalLayout.addWidget(self.table_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 27))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_edit = QtWidgets.QMenu(self.menubar)
        self.menu_edit.setObjectName("menu_edit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.act_open = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_open.setIcon(icon)
        self.act_open.setObjectName("act_open")
        self.act_exit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/images/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_exit.setIcon(icon1)
        self.act_exit.setObjectName("act_exit")
        self.act_save = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_save.setIcon(icon2)
        self.act_save.setObjectName("act_save")
        self.act_juxtapose = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/images/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_juxtapose.setIcon(icon3)
        self.act_juxtapose.setObjectName("act_juxtapose")
        self.act_config = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resources/images/config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_config.setIcon(icon4)
        self.act_config.setObjectName("act_config")
        self.menu_file.addAction(self.act_open)
        self.menu_file.addAction(self.act_save)
        self.menu_file.addAction(self.act_exit)
        self.menu_edit.addAction(self.act_juxtapose)
        self.menu_edit.addAction(self.act_config)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.toolBar.addAction(self.act_open)
        self.toolBar.addAction(self.act_save)
        self.toolBar.addAction(self.act_juxtapose)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.act_config)

        self.retranslateUi(MainWindow)
        self.act_exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Сопоставлятор"))
        self.menu_file.setTitle(_translate("MainWindow", "Файл"))
        self.menu_edit.setTitle(_translate("MainWindow", "Правка"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.act_open.setText(_translate("MainWindow", "Открыть"))
        self.act_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.act_exit.setText(_translate("MainWindow", "Выход"))
        self.act_exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.act_save.setText(_translate("MainWindow", "Сохранить"))
        self.act_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.act_juxtapose.setText(_translate("MainWindow", "Сопоставить"))
        self.act_juxtapose.setShortcut(_translate("MainWindow", "Ctrl+J"))
        self.act_config.setText(_translate("MainWindow", "Параметры"))

